tools:
  jdk: 8u121

envs:
  global:
    variables:
      MAVEN_OPTS: -Xmx512M -XX:+ExitOnOutOfMemoryError
      MAVEN_SKIP_CHECKS_AND_DOCS: -Dair.check.skip-all=true -Dmaven.javadoc.skip=true
      MAVEN_FAST_INSTALL: -DskipTests $MAVEN_SKIP_CHECKS_AND_DOCS -B -q -T C1
      
      MAVEN_CHECKS: true
      TEST_SPECIFIC_MODULES: presto-tests
      TEST_OTHER_MODULES: "!presto-tests,!presto-raptor,!presto-accumulo,!presto-cassandra,!presto-hive,!presto-kafka,!presto-mysql,!presto-postgresql,!presto-redis,!presto-docs,!presto-server,!presto-server-rpm"
      PRODUCT_TESTS: true
      HIVE_TESTS: true

  presto-tests:
    variables:
      TEST_SPECIFIC_MODULES: presto-tests

  presto-raptor:
    variables:
      TEST_SPECIFIC_MODULES: presto-raptor

  presto-accumulo:
    variables:
      TEST_SPECIFIC_MODULES: presto-accumulo

  presto-cassandra:
    variables:
      TEST_SPECIFIC_MODULES: presto-cassandra

  presto-db:
    variables:
      TEST_SPECIFIC_MODULES: presto-hive,presto-kafka,presto-mysql,presto-postgresql,presto-redis

flows:
  
  default:
  - call: install
  - call: test

  install:
  - (name Install):
    - ./mvnw -v
    - call: install-specific(presto-tests)
    - call: install-specific(presto-raptor)
    - call: install-specific(presto-accumulo)
    - call: install-specific(presto-cassandra)
    - call: install-specific(presto-db)
    - call: install-others
  
  test:
  - (name Test):
    - call: maven-checks
    - call: test-specific(presto-tests)
    - call: test-specific(presto-raptor)
    - call: test-specific(presto-accumulo)
    - savepoint
    - call: test-specific(presto-cassandra)
    - call: test-specific(presto-db)
    - call: test-others
    
  install-specific: |
    (name %{TEST_SPECIFIC_MODULES})
    if [[ -v TEST_SPECIFIC_MODULES ]]; then
      ./mvnw install $MAVEN_FAST_INSTALL -pl $TEST_SPECIFIC_MODULES -am
    fi

  install-others:
  - |
    (name Other modules)
    if [[ -v TEST_OTHER_MODULES ]]; then
      ./mvnw install $MAVEN_FAST_INSTALL -pl '!presto-docs,!presto-server,!presto-server-rpm'
    fi
  - |
    (name Product tests)
    if [[ -v PRODUCT_TESTS ]]; then
      ./mvnw install $MAVEN_FAST_INSTALL -pl '!presto-docs,!presto-server-rpm'
    fi
  - |
    (name Hive tests)
    if [[ -v HIVE_TESTS ]]; then
      ./mvnw install $MAVEN_FAST_INSTALL -pl presto-hive-hadoop2 -am
    fi

  maven-checks: |
    (name Maven checks)
    if [[ -v MAVEN_CHECKS ]]; then
      ./mvnw install -DskipTests -B -T C1
    fi

  test-specific:
  - |
    (name %{TEST_SPECIFIC_MODULES})
    if [[ -v TEST_SPECIFIC_MODULES ]]; then
      ./mvnw test $MAVEN_SKIP_CHECKS_AND_DOCS -B -pl $TEST_SPECIFIC_MODULES
    fi

  test-others:
  - |
    (name Other modules)
    if [[ -v TEST_OTHER_MODULES ]]; then
      ./mvnw test $MAVEN_SKIP_CHECKS_AND_DOCS -B -pl $TEST_OTHER_MODULES
    fi
#  - |
#    (name Product tests 1)
#    if [[ -v PRODUCT_TESTS ]]; then
#      presto-product-tests/bin/run_on_docker.sh \
#        multinode -x quarantine,big_query,storage_formats,profile_specific_tests,tpcds
#    fi
#  - |
#    (name Product tests 2)
#    if [[ -v PRODUCT_TESTS ]]; then
#      presto-product-tests/bin/run_on_docker.sh \
#        singlenode-kerberos-hdfs-impersonation -g storage_formats,cli,hdfs_impersonation,authorization
#    fi
#  - |
#    (name Hive tests)
#    if [[ -v HIVE_TESTS ]]; then
#      presto-hive-hadoop2/bin/run_on_docker.sh
#    fi
